Jima-J9M1/Eduvi-E-learning

package-lock.json
package.json
postcss.config.js
src/App.tsx
src/index.css
tailwind.config.js
yarn.lock

In this pull request, we have introduced Tailwind CSS configuration and added initial styling to enhance the visual appeal of the project.
- Integrated Tailwind CSS into the project, enabling powerful utility-first styling.
- Created a Tailwind configuration file for fine-tuning the styling framework.
- Demonstrated the usage of Tailwind classes to showcase the visual improvements.
- Applied Tailwind classes to key elements, providing a preview of the enhanced styling.

Tailwind Configuration and Styling

---

package-lock.json
package.json
postcss.config.js
src/App.tsx
src/index.css
tailwind.config.js
yarn.lock

In this pull request, we have introduced Tailwind CSS configuration and added initial styling to enhance the visual appeal of the project.
- Integrated Tailwind CSS into the project, enabling powerful utility-first styling.
- Created a Tailwind configuration file for fine-tuning the styling framework.
- Demonstrated the usage of Tailwind classes to showcase the visual improvements.
- Applied Tailwind classes to key elements, providing a preview of the enhanced styling.

# PR: Tailwind Configuration and Styling

---

package-lock.json
package.json
src/App.tsx
src/Pages/ErrorPages/404.tsx
src/Pages/Home.tsx
src/Utils/routes.tsx
src/index.css
src/main.tsx
yarn.lock

In this pull request, I have integrated three essential libraries, namely React Query, Material UI, and React Router, to enhance the project's functionality, user interface, and navigation capabilities.
- Integrated React Query to efficiently manage and fetch data from APIs, improving data fetching performance and caching.
- Incorporated Material UI to enhance the visual design and user experience with a set of pre-styled components and theming.
- Implemented React Router to enable seamless navigation between different sections of the application, improving user interaction.

PR: Integration of React Query, Material UI, and React Router

---

package-lock.json
package.json
yarn.lock

In this pull request, I've added the Axios library to our project to streamline the process of making HTTP requests for data fetching. Axios is a widely-used, promise-based HTTP client for the browser and Node.js that simplifies handling asynchronous requests.
- Added Axios as a dependency in the project's `package.json`.

Add Axios for Data Fetching

---

src/Components/Common/Cards/Testimonial.tsx
src/Components/Common/Carousel/TestimonialCarousel.tsx
src/Pages/Home.tsx
src/index.css

This pull request includes several improvements to enhance the website's responsiveness, typography, and layout. The changes made focus on the testimonial section, font consistency, and padding adjustments on the homepage.
1. **Responsive Testimonial Section:** The testimonial section has been updated to be responsive, ensuring a better user experience across different devices and screen sizes.
2. **Global Font Update:** The font throughout the website has been changed to Open Sans to achieve a consistent and visually appealing typography style across all pages.
3. **Padding Reduction on Homepage:** The padding on the homepage has been reduced to improve the overall spacing and alignment of elements, contributing to a cleaner and more balanced layout.

Pull Request: Improvements to Testimonial Section, Font, and Padding

---

src/Components/Common/Cards/courseVideoSectionCard.tsx
src/Pages/Home.tsx
yarn.lock

made Course video section card
- it have propes
- uses flex and grid

add Course video section card

---

package.json
src/Components/Common/Breadcrumbs.tsx
src/Components/Common/Carousel/TestimonialCarousel.tsx
src/Components/Common/CourseCard.tsx
src/Pages/Home.tsx
src/Utils/routes.tsx
src/types.d.ts
yarn.lock

I've added breadcrumb components for navigation in the project. This will enhance the user experience by providing clear navigation paths within the application.
- Created a Breadcrumbs component that dynamically generates breadcrumb links.
- Styled the breadcrumbs using Tailwind CSS for a clean and simple look.
Breadcrumbs are an essential part of navigation. They help users understand where they are in the application's hierarchy and how to navigate back.

Add breadcrumb feature

---

src/Components/Common/Breadcrumbs.tsx
src/Pages/Home.tsx
src/Utils/routes.tsx
yarn.lock

- Update Breadcrumbs using materialUi component.
- Breadcrumbs helps user to navigate easily in the platform.

Update Breadcrumbs with MaterialUi

---

src/App.tsx
src/Components/Common/Cards/ApplyCard.tsx
src/main.tsx
tailwind.config.js

This pull request aim to create an Apply card and to optimize the responsive styling of the card component.
- Create an Apply card with material ui and tailwind
- Repetitive conditionals for screen sizes using useMediaQuery.
- Cleaned up and format.

fix the repsonsiveness of the Apply card

---

src/App.tsx
src/Components/Common/Cards/ApplyCard.tsx
src/Components/Common/CourseCard.tsx
src/Components/Common/HeaderContainer.tsx
src/Pages/Home.tsx
src/main.tsx
tailwind.config.js

This pull request aim to add a container to breadcrumbs and other head components.
- Create a container and put BreadCrumbs and other children.
- Use tailwind and material ui for design.

bread crumbs container

---

src/Components/Common/Pagination.tsx
src/types.d.ts
yarn.lock

- total posts, and how many posts in page ,function to change page and current page from all courses

adding Pagination

---

src/Components/Common/Nav.tsx
src/Pages/Allcourses.tsx
src/Pages/CoursesDetails.tsx
src/Utils/routes.tsx
yarn.lock

Title: Add Dynamic Routing Functionality
Description:
This pull request adds dynamic routing functionality to the project, allowing for more flexible and customizable routes. This feature enhances the overall user experience and expands the capabilities of the application.

Dynamicroute

---

src/Utils/api.tsx

Add workflow

---

src/Utils/api.tsx

Test Workflow

---

.github/workflows/deploy.yaml
index.html

- Change system title
- Change system logo

change title and logo of the app

---

src/Components/Ui/selecte.tsx

- Change navigation bar 
- Change the category choose

Change Navigaiton bar

---

.github/workflows/deploy.yaml

fix: login & Registration modal.
Update: Responsiveness

update github deploy file

---

src/Api/courselist-api.ts
src/Components/Common/Courselist.tsx
src/Components/Common/Nav.tsx
src/Components/Ui/selecte.tsx

PR Title:
Feature: Categories API Integration with Axios and Custom React Query
PR Description:
Overview
=> This pull request introduces a new feature to seamlessly integrate the Categories API using Axios and a custom React Query setup. The primary goal is to enhance data fetching and management, providing a smoother user experience.
Changes Made
=> Categories API Integration: Implemented Axios to interact with the Categories API, allowing efficient retrieval and updating of category-related data.
=> Custom React Query Setup: Introduced a custom React Query configuration tailored to our project's needs. This optimizes caching, background data fetching, and error handling for a more robust client-side data management.
=> Token Dependency: The integration is designed to require only a …

categories-Api

---

src/Components/Common/Cards/Landing.tsx
src/Components/Common/CourseCard.tsx
src/Components/Common/Nav.tsx
src/Components/Forms/SignupForm.tsx
src/Components/Ui/popover.tsx
src/Pages/ApplicantForm/ApplicationForm.tsx
src/Utils/routes.tsx
src/index.css
src/styles/global.css

Title:
Merge the Application form to the development branch
Context:
- Create an application form used for students to register.
- The form contains input area resume, essay, and portfolio link(optional) and apply button.
Tools used:
- Tailwind for styling the form.
- React and typescript

creat an application form

---

src/Api/courselist-api.ts
src/Components/Common/Courselist.tsx
src/Components/Modals/AuthModal.tsx
src/Components/Ui/selecte.tsx
src/Pages/ApplicantForm/ApplicationForm.tsx

fix some issues

---

src/Api/authenticate.ts
src/Api/courselist-api.ts
src/Api/user-api.ts
src/Components/BreadCrumbs/BreadCrumbs.tsx
src/Components/BreadCrumbs/HeaderContainer.tsx
src/Components/Common/Checkbox/LabeledCheckbox.tsx
src/Components/Common/CourseCard.tsx
src/Components/Common/Courselist.tsx
src/Components/Common/Forms/NameField.tsx
src/Components/Common/Forms/PasswordField.tsx
src/Components/Common/Nav.tsx
src/Components/Common/coursePlaylists.tsx
src/Components/Course/ButtonList.tsx
src/Components/Course/CourseDetail.tsx
src/Components/Course/CourseListed.tsx
src/Components/Forms/SigninForm.tsx
src/Components/Forms/SignupForm.tsx
src/Components/Modals/AuthModal.tsx
src/Components/Ui/selecte.tsx
src/Pages/AllCourses/AllCourses.tsx
src/Pages/ApplicantForm/ApplicationForm.tsx
src/Pages/CourseDetails/CourseDetails.tsx
src/Utils/routes.tsx
src/styles/global.css
src/types.d.ts

- Add a Pay Now button on the course detail page.
- Update the button list on the course page with category names.

Jima j9 m1.fix bugs

---

package-lock.json
src/Components/Common/Cards/CourseVideoSectionCard.tsx
src/Components/Common/Cards/Landing.tsx
src/Components/Common/CourseCard.tsx
src/Components/Common/Courselist.tsx
src/Components/Common/Nav.tsx
src/Components/Course/CourseListed.tsx
src/Components/Course/SimilarCourses.tsx
src/Components/Forms/toggleButton.tsx
src/Components/Modals/AuthModal.tsx
src/Components/Ui/popover.tsx
src/Pages/CourseDetails/CourseDetails.tsx
src/Pages/Home/Home.tsx
src/types.d.ts
tailwind.config.js
tsconfig.json
yarn.lock

Subject: PR: Enhancements for Apply to Internship, Sign Up, and Responsiveness
I hope this message finds you well. I am excited to present the latest set of enhancements I've made to our platform. Below is a summary of the changes included in this pull request:
1 Apply to Internship Button:
Moved the "Apply to Internship" button from the home page to the course details page.
This adjustment aims to streamline the user experience, providing a more intuitive flow for individuals interested in specific courses.
2 Sign Up Button:
Added a new "Sign Up" button with corresponding functionality.
Users can now easily register for an account, enhancing our platform's accessibility and user engagement.
Responsiveness Improvements:
3 Adjusted the responsiveness of the home page, courses page, and …

Seid yesuf

---

src/Components/Common/CourseCard.tsx
src/Components/Common/Nav.tsx
src/Components/Common/SubscriptionBox.tsx
src/Components/Common/coursePlaylists.tsx
src/Components/Course/ButtonList.tsx
src/Components/CourseListComponent.tsx
src/Components/Forms/SigninForm.tsx
src/Pages/CourseDetails/CourseDetails.tsx
tsconfig.json

fixing bugs

---

package.json
src/Api/user-api.ts
src/Pages/CourseDetails/CourseDetails.tsx
yarn.lock

add error message

---

src/Api/authenticate.ts
src/Pages/CourseDetails/CourseDetails.tsx

fix data and add payment

---

src/Api/authenticate.ts
src/Api/courselist-api.ts
src/Components/BreadCrumbs/HeaderContainer.tsx
src/Components/Buttons/InternButton.tsx
src/Components/Common/Cards/CourseVideoSectionCard.tsx
src/Components/Common/coursePlaylists.tsx
src/Components/Course/SimilarCourses.tsx
src/Pages/CourseDetails/CourseDetails.tsx
src/types.d.ts

update payment method url

---

src/Api/authenticate.ts
src/Api/user-api.ts
src/Pages/CourseDetails/CourseDetails.tsx

add the logic behind access the data

---

src/Api/authenticate.ts
src/Components/Forms/SigninForm.tsx
src/Components/Forms/SignupForm.tsx
src/Components/Forms/toggleButton.tsx
src/Components/RequiredAuth.tsx
src/Pages/CourseDetails/CourseDetails.tsx

fix issues

---

src/Api/internApplication.ts
src/Pages/ApplicantForm/ApplicationForm.tsx

This PR adds a simple React component for file uploads using Axios and FormData.
- Added a new React component (`FileUploadComponent`) for file uploads.
- Integrated Axios for making a POST request to the specified API endpoint.
- Used the FormData approach to handle file uploads.

  intern apllication functionaltiy

---

src/Api/authenticate.ts
src/Components/Common/Cards/CourseVideoSectionCard.tsx
src/Components/Common/CourseCard.tsx
src/Components/Common/Courselist.tsx
src/Components/Common/Nav.tsx
src/Components/Forms/SigninForm.tsx
src/Components/Forms/SignupForm.tsx
src/Components/Forms/toggleButton.tsx
src/Components/RequiredAuth.tsx
src/Pages/CourseDetails/CourseDetails.tsx
src/Utils/Contexts/ModalContext.tsx

Fix payment method

---

src/Api/user-api.ts
src/Components/Forms/SigninForm.tsx

redirect user after the registration

---

src/Api/internApplication.ts
src/Pages/ApplicantForm/ApplicationForm.tsx
src/Pages/CourseDetails/CourseDetails.tsx

- i handle resume by onchange and i made it's on validation and error
- Used the FormData approach to handle file uploads.

intern Form

---

src/Components/Common/Forms/NameField.tsx
src/Components/Forms/SigninForm.tsx
yarn.lock

add regex to phone number

---

src/Pages/ApplicantForm/ApplicationForm.tsx
src/Pages/CourseDetails/CourseDetails.tsx
tailwind.config.js

in this PR the first thing I made is I save the course that I get from the state  in Local storage  and whenever there is the state it rewrites the local storage
b/c of this I can redirect from anywhere to the course details page 
the second thing is I redirect users from the application page to the course details page

working with local storage

---

src/Components/Common/Cards/ApplyCard.tsx
src/Components/Common/Cards/SimilarCourseCard.tsx
src/Components/Common/Nav.tsx
src/Components/Course/SimilarCourses.tsx
src/Pages/CourseDetails/CourseDetails.tsx
src/types.d.ts

in this PR I made
1, I change the text of apply card
2, the functionality of similar course
3, and I also made the logo that was found on navBar to navigate to the home page

SimilarCourse

---

src/Components/Course/CourseListed.tsx
src/Components/Course/SimilarCourses.tsx

in this PR i made pagination for similar  courses

pagination
